[package]
name = "rust-nes"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = { version = "2.4.0", features = ["example_generated"] }
once_cell = "1.18.0"
rand = "0.8.5"
sdl2 = "0.35.2"
